### ISSUE TITLE
FF: missing, stable ships FF-ESR

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#1]

**Comment by star-buck** [comment]
lets ship that on core

**Comment by llelectronics** [comment]
Should be there in next ISO: https://github.com/netrunner-core/netrunner-core/commit/489e7d97d2c8809031dec346e53bb2dbb5040760
Panel fix: https://github.com/netrunner-artwork/artwork-lnf-netrunner-core/commit/bb5947a1dd765d77032e216447ffb69c760374e8
