### ISSUE TITLE
Apply Core LNF theme correctly, so its got Breeze icons, breeze window deco, etc.

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#12]

**Comment by llelectronics** [comment]
Should be fixed with: https://github.com/netrunner-core/netrunner-core-settings/commit/370cbdc277523d9daf3e611bf0fcba2660fd5c2d
and 
https://github.com/netrunner-core/netrunner-core-settings/commit/d7558e28d7652068c9b57442ada52ae1646ae814

**Comment by star-buck** [comment]
please add green label, thanks.
