### ISSUE TITLE
FF: starting it has an active left sidebar showing ublock

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#18]

**Comment by llelectronics** [comment]
Fixed with: https://github.com/netrunner-common/netrunner-settings-firefox/commit/9859005235196bffb2ed90c5a46822830538d856

**Comment by llelectronics** [comment]
Not really fixed. Initially there is no sidebar but it keeps loading after a while. 
edit: No clue how to get rid of this.

**Comment by star-buck** [comment]
i wonder if it magically fixed itself with latest core ISO?

**Comment by llelectronics** [comment]
Seems fixed.
