### ISSUE TITLE
FF-ESR: doesnt have the plasma integraton addon (should we switch to non-esr now that we use buster?)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#19]

**Comment by llelectronics** [comment]
A mistake. The extension is only visible for the normal FIrefox version not FF-ESR. 
I recommend sticking with FF-ESR for Core as this version gets auto updated with security updates by Debian.

**Comment by shadeslayer** [comment]
Regular FF is not available for testing, but only in Sid. This is on purpose. I agree that we should stick to ESR.

**Comment by zgrimshell** [comment]
FYI FF packages are pretty standalone so you can mirror/add something from (which is officially used for builds) from http://mozilla.debian.net/

**Comment by star-buck** [comment]
How we have FF in desktop?

**Comment by llelectronics** [comment]
> How we have FF in desktop?

We imported the SID package to our plasmazilla component in repo

**Comment by star-buck** [comment]
Oh okay. So how does it get any updates?

**Comment by llelectronics** [comment]
It doesn't (its basically stuck at the same version forever. Like we did for previous releases)

**Comment by shadeslayer** [comment]
@zgrimshell mozilla.debian.net instructs us to add the debian unstable repo to get Firefox. I don't think that's feasible for us

**Comment by star-buck** [comment]
Yeah, we want stable only.
