### ISSUE TITLE
simplemenu: missing/not working, lets use dash

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#2]

**Comment by shadeslayer** [comment]
I doubt we'll be able to make simplemenu work reliably with a older plasma release. I recommend that we switch to a different launcher.

**Comment by star-buck** [comment]
Is simplemenu packaged in stable itself?

**Comment by star-buck** [comment]
lets use dash then default

**Comment by llelectronics** [comment]
Applied: https://github.com/netrunner-artwork/artwork-lnf-netrunner-core/commit/17d72b8a448a6c0ad0102d0733c3062aefe59b21
