### ISSUE TITLE
Software-Properties creates /etc/apt/trusted.gpg

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-core-releases#23]
software-properties like on desktop creates a /etc/apt/trusted.gpg file everytime it is opened. 
This causes a big fat warning on apt update and in synaptc. 

On Desktop I did a nasty workaround by adding a hook which downloads the Ubuntu version of software-properties which does not suffer from this. 

We need to find a way to ether fix this asap in Debian Testing (its in soft freeze and would be a shame to have this bug in soon to be stable) or rebuild it with a fix just for Netrunner.

**Comment by shadeslayer** [comment]
Waiting on juliank to upload a new version of the package. I've pinged him again just now.

**Comment by llelectronics** [comment]
The new version is waiting in Debians queue to be accepted in experimental. 
Local builds of the source shows that it is indeed working without creating a broken trusted.gpg file. 

As it will take a bit longer for it to be imported to Debian and Testing (not sure if it will land in buster even) I copied the code over here: https://github.com/dci-extras-packaging/software-properties
It just needs adding to dci to build and land in our repos.

**Comment by star-buck** [comment]
This is a great usecase for you and Scarlett to see in detail how this is
done for dci.

**Comment by ScarlettGatelyMoore** [comment]
Unfortunately I am heading out soon for appointment, but I am almost positive that running job-updater.rb in pangea-tooling will achieve this. There are flags that need to be passed that can be determined in the code.

**Comment by llelectronics** [comment]
Yes I ran the `jenkins_jobs_update.rb --ci dci` code already. Now the question should it pick the repo up immediately after that? If yes this isn't the case.

**Comment by star-buck** [comment]
@llelectronics : is fixed?

**Comment by llelectronics** [comment]
Yes

**Comment by star-buck** [comment]
was missing green label, thats why i asked
