### ISSUE TITLE
Reminder: Cala: hide "resize_fs" module again, as it is no longer needed for visual control

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#31]
- instead an info that its doing a resize would be sufficient during installation and slideshow
- this affects ARM versions

**Comment by star-buck** [comment]
this is a reminder that in the next days we should look into a more proper, non-debugging looking way of handling the resize visually either with a module or part of whole installation procedure.

**Comment by llelectronics** [comment]
This is fixed for zeronet already. But wasn't fixed for C1 Core version. 
Done this now: https://github.com/netrunner-odroid/c1-calamares-core/commit/3cea47c1d3e74206bc560e790091a7d94dd970c4
