### ISSUE TITLE
Core: Wallpapers: img from yesterday shipped wrong wallpapers (will test new ISO later tonight)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#34]
on there is  OLD idolon and wrong Z2:
![screenshot_20190208_174614](https://user-images.githubusercontent.com/840070/52492489-98978b00-2bc9-11e9-98e2-dd096f96afe6.png)

**Comment by llelectronics** [comment]
Yes we install the old idolon wallpaper as specified for 18.08 and did not change this so far. So even the latest ISO includes this wallpaper. 
The default wallpaper is correctly set to Netrunner Core though for the latest ISO.

**Comment by star-buck** [comment]
please remove 1803 idolon wallpaper (obvsiously this wouild have been changed for 1808 if it was close to release as with 1901 Desktop and every series-specific wallpaper before)

**Comment by star-buck** [comment]
looks good
