### ISSUE TITLE
windows decorations: remove "context help" button from being active/selected (likely affects all core (or even desktop) versions?)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#38]
even though one cannot see it due to preview bug, one can see the "?" button is active in the system settings window deco itself:
![snap 2019-01-30 at 23 56 34](https://user-images.githubusercontent.com/840070/52018753-c0149680-24eb-11e9-9b42-fcd54bbfa496.png)

**Comment by star-buck** [comment]
@llelectronics : was this only core versions or desktop too?

**Comment by llelectronics** [comment]
Only core as desktop has this already here: https://github.com/netrunner-desktop/netrunner-desktop-settings/commit/48bd43e97131c942597d34eb6e41f7ff22d9b4b7

**Comment by star-buck** [comment]
latest img c1:
![snap 2019-02-11 at 16 10 31](https://user-images.githubusercontent.com/840070/52593500-68f6b600-2e49-11e9-9a87-4e85d627eec6.png)
