### ISSUE TITLE
remove additional wallpapers

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#39]
at least on C1, not sure why those ended up on there default or after an update:
![snap 2019-02-12 at 19 05 54](https://user-images.githubusercontent.com/840070/52657699-87b48580-2ef9-11e9-8570-4b21e38e38b0.png)

**Comment by llelectronics** [comment]
Yeah a typo apparently. Fixed with: https://github.com/netrunner-zeronet/c1-live-build-zeronet/commit/28c5f7de09293dac2af503ce60ef06fcf6b88aed
