### ISSUE TITLE
ff-esr: plasma integration package error

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#40]
![snap 2019-02-13 at 23 11 27](https://user-images.githubusercontent.com/840070/52747711-ca06c100-2fe4-11e9-936d-73f281cdefb5.png)

**Comment by kbroulik** [comment]
Is that package installed? Is the `plasma-browser-integration-host` binary available? Does the config file in /usr/share/mozilla/native-messaging-hosts point to the correct binary?
