### ISSUE TITLE
C1: update all packages for new img

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#42]

**Comment by ScarlettGatelyMoore** [comment]
Hi, I am acknowledging this. I read it as, new packaging in Netrunner repos, but I guess you mean you want a new image? @llelectronics says we need to wait for calamares to land back in debian. If you still want one I need @llelectronics to teach me how to make an image. I have never made one.

**Comment by star-buck** [comment]
@ScarlettGatelyMoore : yes, this would be good for the meeting to look into.

**Comment by star-buck** [comment]
@llelectronics : lets update all packages to latest on the C1 core img, so that there are no pending updates after install.

**Comment by llelectronics** [comment]
Just adding this as info. This is the consequence of C1 images based on buster and not a snapshot. This issue will reappear as soon as debian releases Updates after we built our image.

**Comment by star-buck** [comment]
Yes sure, still we can update from time to time and do a 19.01.1 iso/img
change during the two years release cycle.
