### ISSUE TITLE
C1: installer doesnt resize partition

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#44]

**Comment by llelectronics** [comment]
Tested it a few times. Resizing works for me with the SanDisk Extreme U3 A1 64GB card. 
I assume the timeout for the command to finish might be to short for your card maybe.

**Comment by star-buck** [comment]
It was a normal 16GB disk that i used for last C1 fine too (the one we
shipped with 17.01).

**Comment by llelectronics** [comment]
Very strange. Can you retry it with that card and running calamares from terminal with debug mode to see if the resizing script is sending a return 0 or if it aborts because of the timeout.

**Comment by star-buck** [comment]
Sure, will flash the card again and debug.

**Comment by star-buck** [comment]
nach installation und neustart des letzten img:
![Snap 2019-04-08 at 21 33 45](https://user-images.githubusercontent.com/840070/55751499-1e0eae80-5a46-11e9-9a43-0257d6d7fc02.png)
![Snap 2019-04-08 at 21 33 57](https://user-images.githubusercontent.com/840070/55751501-1fd87200-5a46-11e9-82b1-6de77cb3e63b.png)

Dolphin zeigt nur 2.3GB frei an. Wieso kann Calamares manchmal nicht formattieren?
Hat es etwas damit zu tun, wenn man auf dem live system vorher zuviel startet, z.b. Firefox etc. beinflusst das den installationsprozess, vielleicht durch das zram?
Auf jeden Fall kann ich so den C1 nicht verschicken, wir wollten unbedingt dieses Calamares Resize Problem herausfinden und beheben. Vielleicht das alte modul wo es angezeigt wurde wieder reinhängen?
Was kann ich auf dem IMG jetzt tun, um etwas herauszufinden?

**Comment by star-buck** [comment]
@adriaandegroot @llelectronics @davidedmundson 
does this all look normal after installation, but the not expanded size?
![Snap 2019-04-08 at 21 40 07](https://user-images.githubusercontent.com/840070/55751868-f704ac80-5a46-11e9-9a05-5be5d407a061.png)

**Comment by star-buck** [comment]
thats c1 core system after calamares install btw.

**Comment by llelectronics** [comment]
Something seems to be wrong. I cannot reproduce it. I tried 3 microsd cards today. Resizing worked without any issue.
Have you restarted via the calamares reboot option after it finished the installation? 
Have you tried another microsd card just to be sure it isn't that specific card. 
What about the fsresizer module stuff that we talked on telegram about? Have you tried that yet? It worked for me aswell

**Comment by star-buck** [comment]
I thought you switched to that already!!

**Comment by llelectronics** [comment]
I was testing this during the IMG build. This IMG has a higher timeout for the deffered_resize module only.

**Comment by star-buck** [comment]
im trying some other method to flash the img to card, maybe diskimager is bonkers for latest img...

**Comment by star-buck** [comment]
works with fsresizer:
![Snap 2019-04-10 at 01 22 46](https://user-images.githubusercontent.com/840070/55841431-6229ae00-5b2f-11e9-9b21-49744875e378.png)
