### ISSUE TITLE
FF-ESR: in-program font seems to be very thin, config not applied correctly?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#5]

**Comment by llelectronics** [comment]
You mean the menu and bookmark entries? 
The fonts on websites look ok to me. 
Reapplying the GTK-Font Settings fixes the issue with menu and bookmark entries.

**Comment by llelectronics** [comment]
This commit is the cause of the "weird" fonts in firefox. We changed it deliberately for all gtk-3.0 apps
https://github.com/netrunner-common/netrunner-settings-theming/commit/6a97b0e1eeb932f1f1e37263980d6530b47336d7

Should I revert this commit?

**Comment by star-buck** [comment]
FF font in 18.03 Idolon seems okay though?

**Comment by llelectronics** [comment]
Strange then. Changing it back and the fonts look ok
