### ISSUE TITLE
FF-ESR: needs ESR configs applied (instead of quantum ones)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#6]

**Comment by llelectronics** [comment]
Firefox-ESR in Debian seems to be broken in general as it ignores its own config files in /etc/firefox-esr. 
This bug report covers it partly (I send my notes to it): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828050
Workaround is in place now which should fix the issue for us for now: https://github.com/netrunner-common/netrunner-settings-firefox/commit/432a58622d24b90b9f5b75b1533a04f75d578b17
