### ISSUE TITLE
Systemsettings kservices need update (broken modules)

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-core-releases#7]
Systemsettings look a bit weird with the "old" icon view (too many catgeories and some icons look out of place). Fonts & Font Settings which includes Fonts module for example. 
Some modules are not working/accessible like Workspace Behavior -> Workspace. 

- Touchscreen
- Network Settings -> Connections
- Input Devices -> Mouse
- Others -> Launch Feedback
- Others -> Systemd

**Comment by NuLogicSystems** [comment]
I already updated this in github for Plasma 5.13.
If your still packaging for 5.12.x, you'll need to use the prior commit from February.
https://github.com/ds9-common/default-systemsettings-settings/commits/master

**Comment by llelectronics** [comment]
We are packaging for Plasma 5.8 now in Netrunner Core :P

**Comment by NuLogicSystems** [comment]
Hmm, I'm not that familiar with Debian packaging.
Can you not cherry pick during packaging?

I do apologize, I was just trying to do as I was instructed.

**Comment by llelectronics** [comment]
We could do a configuration especially for Plasma 5.8 but I think starbuck wants it also to live in a separate git repo then. 
So we'll see.

**Comment by NuLogicSystems** [comment]
Well, systemsettings for Rolling is also in a separate git repo, but I was asked to "see if you can copy them over to the netrunner debian repos."

On retrospect, maybe I should have made a separate branch for these upstream changes to Plasma 5.13.

**Comment by llelectronics** [comment]
It is not your fault at all. We made the decision for Netrunner Core to use Debian stable as base instead of testing. This means instead of Plasma 5.13 -> Plasma 5.8. 
Though we still have Plasma 5.13 for the "normal" Netrunner version (the non core one) so that it is very useful to have those changes for it. 
As we just started basically on Netrunner Core development. I added this task purely as reminder that we don't forget to fix stuff with systemsettings.

**Comment by NuLogicSystems** [comment]
Just a thought , but couldn't you just pull from the netrunner/18.03 branch?
It's at the commit right before I made those changes.

**Comment by llelectronics** [comment]
We'll see. I am not convinced that this will even work with Plasma 5.8. But that needs testing first.

**Comment by shadeslayer** [comment]
We can potentially ship the customised version of the desktop file in the netrunner-core specific settings path?

**Comment by llelectronics** [comment]
Yes we can do this. We just need to make sure it is prioritized over the ds9 one

**Comment by shadeslayer** [comment]
Everything in usr/share/netrunner-core-settings/plasma5-profile/ is prioritised over usr/share/default-settings/plasma5-profile/
