### ISSUE TITLE
about: change OS Version to "Netrunner Core 19.01"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-core-releases#8]

**Comment by llelectronics** [comment]
Done with this commit: https://github.com/netrunner-core/base-files/commit/deb61d1e21023fcfa9055d79ce5d9101b9fe416d

**Comment by star-buck** [comment]
remove "- Idolon" though:
![snap 2018-07-25 at 10 05 21](https://user-images.githubusercontent.com/840070/43187669-5c55f96a-8ff2-11e8-8b0d-2c9553c81e5e.png)

**Comment by llelectronics** [comment]
Done: https://github.com/netrunner-core/base-files/commit/fbed00134bed651370b9294c69d9e065a87878e9
